//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaLiangWindow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Factory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Factory()
        {
            this.T_User = new HashSet<T_User>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid FK_FactoryType { get; set; }
        public string Remark { get; set; }
        public bool IfEnable { get; set; }
        public bool IfDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual T_FactoryType T_FactoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_User> T_User { get; set; }
    }
}
